language: node_js
node_js:
  - "8.9.4"
before_script:
  - yarn

script:
  - yarn build --base-href https://RichardMatsen.github.io/mwb-v2-redux/


branches:
  only:
  - master

cache:
  directories:
    - node_modules
